name: Build Container

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    concurrency: 
      group: "build-container"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.10.0
      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Setup Pack
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli && \
          sudo apt-get update && \
          sudo apt-get install pack-cli
      - name: Get Short SHA
        id: shortsha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ./pack-cache
          key: "${{ hashFiles('build.gradle') }}"
      - name: Build Container
        run: |
          pack build --publish ghcr.io/${{github.repository}}:${{ github.sha }} -t ghcr.io/${{github.repository}}:latest \
            -t ghcr.io/${{github.repository}}:${{ steps.shortsha.outputs.sha_short }} -B paketobuildpacks/builder-jammy-base --cache='type=build;format=bind;source=./pack-cache'

